version: '3'

services:
  telegram_bot:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./etc/docker/Dockerfile
    ports:
      - "8666:8666"
      - "4040:4040"
    container_name: telegram_bot
    volumes:
      - .:/app/main

  redis:
    image: redis:latest
    container_name: redis
    ports:
        - "6379:6379"
